# Generated by Django 3.1.12 on 2022-05-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_categary_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categary',
            name='dt',
            field=models.DateTimeField(),
        ),
    ]
