# Generated by Django 3.1.12 on 2022-05-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220524_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categary',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
    ]
