# Generated by Django 3.1.12 on 2022-05-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='primium',
            new_name='premium',
        ),
    ]
