# Generated by Django 3.1.12 on 2022-06-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='asked_date',
            new_name='dt',
        ),
    ]
