# Generated by Django 3.1.12 on 2022-06-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20220601_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='dt',
            new_name='creation_date',
        ),
    ]
