# Generated by Django 3.1.12 on 2022-06-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20220601_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Question1',
        ),
    ]
